# Site settings
title: Authing 官方博客 | 云端身份认证系统
description: "Authing云端身份认证系统官方博客"
url: "https://authing.cn/blog"
author:
  name: "Authing 官方博客 | 云端身份认证系统"
  email: "xieyang@dodora.cn"
  url: "https://authing.cn"

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
